[package]
name = "ipceed-types"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true, features = ["rc"] }
uuid = { workspace = true, features = ["serde"] }
async-trait.workspace = true
